### ISSUE TITLE
make docker-build output does not go in build directory

### ISSUE THREAD

**Issue by eriknstevenson** [tribesat/firmware#2]
Just noticed that the docker-build make command creates a build directory, but the object, hex, and elf files all just end up in the base directory. Not sure if this is intended behavior, but in any case I found it to be slightly confusing.

**Comment by kelvinabrokwa** [comment]
@narrative you're right, thats a mistake. ~I'll move the build assets into the build directory.~ I'll remove the build directory.

**Comment by kelvinabrokwa** [comment]
done in https://github.com/tribesat/firmware/pull/3
