### ISSUE TITLE
Implement radio beacon packets

### ISSUE THREAD

**Issue by kelvinabrokwa** [tribesat/firmware#9]
We get 13 bytes in each beacon for our data.

1) Decide what goes into those bytes
2) Implement payload logic for setting those
3) Implement modem emulator logic for reading those bytes periodically
4) Set up Arduinos for testing - there will be 6 analog inputs, each setting 2 byte, and 2 digital inputs, setting 1 byte

**Comment by wdconinc** [comment]
Those are more hardware functions, outside of firmware control. They are analog signals to be provided to the modem for digitization.

**Comment by kelvinabrokwa** [comment]
@wdconinc ah I see. In that case I'll close this issue 👍
